export default {
  MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
  MARK_ALL_NOTIFICATION_AS_READ: 'MARK_ALL_NOTIFICATION_AS_READ',
  START_NOFICATION_LOADING: 'START_NOFICATION_LOADING',
  FINISH_NOFICATION_LOADING: 'FINISH_NOFICATION_LOADING',
  RECIVED_NOTIFICATIONS: 'RECIVED_NOTIFICATIONS',
  START_LOGIN: 'START_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED'
}